class Config:
    valid_email="dannymcm@ibm.com"
    valid_password="testing010"
    invalid_email="tester123@qa.com"
    invalid_password="test@123xyz"
    product_name = "Nikon D300"
    product_quantity = "1"
    total_price = "$98.00"
    #address book fields
    first_name="O.J."
    last_name="Simpson"
    address="287 Main Street"
    city="Buffalo"
    zipcode = "14221"
    country="Italy"
    region="Pesaro e Urbino"
    first_name1 = "Aaron"
    last_name1 = "Rogers"
    address1 = "287 Niagara Falls avenue"
    city1 = "Pittsburgh"
    zipcode1 = "40015"
    country1 = "United States"
    region1 = "Ohio"

